"""empty message

Revision ID: 6cb2f38e194b
Revises: b0aa98e65986
Create Date: 2024-02-21 14:10:28.361325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb2f38e194b'
down_revision = 'b0aa98e65986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_table', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
